POST http://localhost:8081/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdHVzZXI4OEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgxODI1NCwiZXhwIjoxNzA0ODIwMDU0fQ.QOge_2-mGAHk86kAwtPtpd912Tq5K5zTa2lbbAZBWEU

{
    "text": "Test post on January 9, 2024"
}

###

GET http://localhost:8081/api/posts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdHVzZXI4OEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgxODI1NCwiZXhwIjoxNzA0ODIwMDU0fQ.QOge_2-mGAHk86kAwtPtpd912Tq5K5zTa2lbbAZBWEU

###

GET http://localhost:8081/api/posts/636683b6b7a919666cf935cd HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdHVzZXI4OEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgxODI1NCwiZXhwIjoxNzA0ODIwMDU0fQ.QOge_2-mGAHk86kAwtPtpd912Tq5K5zTa2lbbAZBWEU

###

PUT http://localhost:8081/api/posts/636683b6b7a919666cf935cd HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdHVzZXI4OEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgxODI1NCwiZXhwIjoxNzA0ODIwMDU0fQ.QOge_2-mGAHk86kAwtPtpd912Tq5K5zTa2lbbAZBWEU

{
    "id": "636683b6b7a919666cf935cd",
    "text": "Slightly modified test post on January 9, 2024"
}

###

DELETE http://localhost:8081/api/posts/659d7699ad77fb08dd378ce5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoidGVzdHVzZXI4OEB0ZXN0LmNvbSIsImlhdCI6MTcwNDgxODI1NCwiZXhwIjoxNzA0ODIwMDU0fQ.QOge_2-mGAHk86kAwtPtpd912Tq5K5zTa2lbbAZBWEU

###